---
---
# See: https://developer.github.com/v3/issues/
issues_numbers = []
api_issue_source = 'https://api.github.com/repos/communityNTNU/Data-for-watchNTNU/issues?'
$.getJSON api_issue_source, (issues) ->
  $.each issues, (k, d) ->

    ###
        Here are the useful shit:
        d.html_url
        d.state
        d.title
        d.number
        d.body
        d.user.login
        d.user.html_url
        d.locked
        d.comments
        d.closed_at
        d.created_at
        d.update_at
    ###

    issues_numbers.push d.number
    # Converted from CoffeeScript: "<div id=\"#{d.number}\"><h1>number=#{d.number}, url=#{d.html_url}, state=#{d.state}, title=#{d.title}, body=#{d.body}, user=#{d.user.login}, user_url=#{d.user.html_url}, locked=#{d.locked}, comment_count=#{d.comments}, closed_at=#{d.closed_at}, created_at=#{}, update_at=#{d.update_at}</h1></div>"
    #var html = "<div id=\"" + d.number + "\"><h1>number=" + d.number + ", url=" + d.html_url + ", state=" + d.state + ", title=" + d.title + ", body=" + d.body + ", user=" + d.user.login + ", user_url=" + d.user.html_url + ", locked=" + d.locked + ", comment_count=" + d.comments + ", closed_at=" + d.closed_at + ", created_at=" + ", update_at=" + d.update_at + "</h1></div>";
    #'<div id="#{d.number}"><h1><a href="#{d.html_url}">#{d.title}</a></h1><h2>user: <a href="#{d.user.html_url}">#{d.user.login}</a></p2><p class="lead">state: #{d.state}</p><p>#{d.body}</p><span class="counter">#{d.comments}</span></div>';
    html = "<div id=\"#{d.number}\"><h1><a href=\"#{d.html_url}\">#{d.title}</a></h1><h2>user: <a href=\"#{d.user.html_url}\">#{d.user.login}</a></p2><p class=\"lead\">state: #{d.state}</p><p>#{d.body}</p><span class=\"counter\">#{d.comments}</span></div>"
    $('#temp').append html
    return
  # See: https://developer.github.com/v3/issues/comments/
  $.each issues_numbers, (i, num) ->
    api_comment_source = 'https://api.github.com/repos/communityNTNU/Data-for-watchNTNU/issues/' + num + '/comments'
    $.getJSON api_comment_source, (comments) ->
      $.each comments, (k, d) ->

        ###
            Here are the useful shit:
            d.body
            d.user.login
            d.user.html_url
            d.created_at
            d.updated_at
        ###

        # Converted from CoffeeScript: "<h2>body=#{d.body}, user=#{d.user.login}, user_url=#{d.user.html_url},, created_at=#{}, update_at=#{d.update_at}</h2>"
        #var html = "<h2>body=" + d.body + ", user=" + d.user.login + ", user_url=" + d.user.html_url + ",, created_at=" + ", update_at=" + d.update_at + "</h2>";
        #'<h3><a href="#{d.user.html_url}">#{d.user.login}</a></h3><p>body=#{d.body}</p>';
        html = "<h3><a href=\"#{d.user.html_url}\">#{d.user.login}</a></h3><p>#{d.body}</p>"
        $('#' + num).append html
        return
      return
    return
  return

# ---
# generated by js2coffee 2.1.0
